### ISSUE TITLE
Firefox 64.0 no mozrepl

### ISSUE THREAD

**Issue by Krisselack** [RenWenshan/emacs-moz-controller#8]
The mozrepl addon is no longer supported. Are there alternatives?

**Comment by RenWenshan** [comment]
Not as I'm aware of.

**Comment by sinekonata** [comment]
So can we use this or not at all any more? How do you manage to do what you did before? Are you using chrome or have you stopped using this tool completely?

**Comment by RenWenshan** [comment]
@sinekonata 
I still use it from time to time by keeping an old version of Firefox. However, more and more websites are becoming funny on it, so I know eventually it will die out.

A more hard-core approach is EAF, which allows you to properly render modern web pages inside Emacs so you have total control, and there has been great progress lately. It has certain limitations though: no i3wm, no Mac, still quite half-baked.

**Comment by sinekonata** [comment]
Yes EAF looks more like what I was looking for but your solution seemed like a cleaner FF experience.
Do you know of this? https://addons.mozilla.org/en-GB/firefox/addon/edit-with-emacs1/reviews/?score=5
It seems to work to date.

**Comment by RenWenshan** [comment]
@sinekonata heard of it, I use GhostText myself (guess they work in a similar way).
